#!/usr/bin/env bash
## proces and pid file
echo $$ > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo I hate the kill command ; exit" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	trap "rm -rf /var/run/myscript.pid ; exit" SIGQUIT
done
