#!/usr/bin/env bash
## proces and pid file
echo $$ > /var/run/myscript.pid
while true
do
	trap 'echo I hate the kill command' SIGTERM
	trap 'echo Y U no love me?!' SIGINT
	trap 'rm -rf /var/run/myscript.pid' SIGQUIT
       	
	echo "To infinity and beyond"
done
